"""GF(2) (binary field) linear algebra utilities.

Used to compute logical operator bases for stabilizer codes: rows/vectors
are binary (mod-2) vectors, matrix multiplication is mod-2, and "addition"
is XOR. These routines back `logical_ops.compute_logical_operators`.
"""

from __future__ import annotations
import numpy as np


def rref(M: np.ndarray):
    """Compute the row-reduced echelon form of `M` over GF(2).

    Standard Gaussian elimination with mod-2 arithmetic: row addition is
    XOR and there is no scaling step (every nonzero element is already 1).

    Args:
        M: 2D array-like, reduced mod 2.

    Returns:
        Tuple `(R, pivot_cols, rank)`:
            R: The reduced row-echelon form, as a uint8 array.
            pivot_cols: List of column indices holding a pivot, in the
                order the pivot rows appear.
            rank: Number of pivots found, i.e. `rank(M)` over GF(2).
    """
    R = (np.asarray(M, dtype=np.uint8) % 2).copy()
    rows, cols = R.shape
    pivot_cols = []
    r = 0
    for c in range(cols):
        if r >= rows:
            break
        piv = None
        for i in range(r, rows):
            if R[i, c]:
                piv = i
                break
        if piv is None:
            continue
        if piv != r:
            R[[r, piv]] = R[[piv, r]]
        mask = R[:, c].astype(bool)
        mask[r] = False
        R[mask] ^= R[r]
        pivot_cols.append(c)
        r += 1
    return R, pivot_cols, r


def rank(M: np.ndarray) -> int:
    """Compute the rank of `M` over GF(2), via `rref`."""
    if M.size == 0 or M.shape[0] == 0:
        return 0
    _, _, r = rref(M)
    return r


def nullspace(M: np.ndarray) -> np.ndarray:
    """Compute a basis for ker(M) over GF(2), i.e. {v : M @ v = 0 mod 2}.

    Uses `rref` to identify pivot columns; each non-pivot ("free") column
    generates one basis vector by setting that free variable to 1 (and all
    other free variables to 0) and back-solving the pivot variables from
    the reduced rows.

    Args:
        M: 2D array-like check matrix.

    Returns:
        uint8 array of shape `(dim(ker M), M.shape[1])`, one basis vector
        per row. Empty (0 rows) if the nullspace is trivial.
    """
    n = M.shape[1]
    R, pivot_cols, _ = rref(M)
    pivot_set = set(pivot_cols)
    free_cols = [c for c in range(n) if c not in pivot_set]
    basis = []
    for fc in free_cols:
        v = np.zeros(n, dtype=np.uint8)
        v[fc] = 1
        for i, pc in enumerate(pivot_cols):
            v[pc] = R[i, fc]
        basis.append(v)
    if not basis:
        return np.zeros((0, n), dtype=np.uint8)
    return np.array(basis, dtype=np.uint8)


def in_rowspace(v: np.ndarray, basis_rref: np.ndarray, pivot_cols) -> bool:
    """Check whether `v` lies in the rowspace spanned by `basis_rref`, over GF(2).

    Reduces `v` against the (already row-reduced) basis by XORing out each
    pivot column in turn; `v` is in the rowspace iff it reduces to zero.

    Args:
        v: 1D binary vector to test.
        basis_rref: Row-reduced echelon basis (e.g. from `rref`).
        pivot_cols: Pivot column indices matching `basis_rref`'s rows, in
            the order produced by `rref`.

    Returns:
        True if `v` is a GF(2) linear combination of `basis_rref`'s rows.
    """
    v = v.copy().astype(np.uint8) % 2
    for i, pc in enumerate(pivot_cols):
        if v[pc]:
            v ^= basis_rref[i]
    return not v.any()


def quotient_basis(H_detect: np.ndarray, H_other: np.ndarray | None = None) -> np.ndarray:
    """Compute a basis for the quotient space ker(H_detect) / rowspace(H_other).

    For a CSS code, logical operators of one type (say Z) are exactly the
    elements of ker(H_X) that are *not* already generated by the stabilizer
    group of the same type (rowspace(H_Z)) — i.e. undetectable operators
    modulo trivial stabilizers. `H_detect` and `H_other` must be a valid
    CSS pair (`H_detect @ H_other.T == 0 mod 2`), since a logical operator
    must commute with all checks it isn't itself built from.

    Greedily walks the nullspace basis of `H_detect` and keeps any vector
    that increases the rank of the running "combined" set beyond
    `H_other`'s span, yielding one representative per independent logical
    degree of freedom.

    Args:
        H_detect: Check matrix whose kernel candidate logical operators
            must lie in (operators undetected by this check type).
        H_other: Stabilizer generators of the same Pauli type to quotient
            out (trivial/stabilizer-equivalent operators). If `None` or
            empty, this reduces to `nullspace(H_detect)`.

    Returns:
        uint8 array of shape `(k, H_detect.shape[1])` — `k` independent
        logical operator representatives, one per row. Empty if there are
        no logical degrees of freedom.

    Raises:
        ValueError: If `H_detect` and `H_other` are not a valid CSS pair.
    """
    null_basis = nullspace(H_detect)
    if H_other is None or H_other.shape[0] == 0:
        return null_basis
    check = (H_detect.astype(np.uint8) @ H_other.astype(np.uint8).T) % 2
    if check.any():
        raise ValueError("Invalid CSS pair: H_detect @ H_other.T != 0 (mod 2).")
    combined = H_other.astype(np.uint8) % 2
    logical_ops = []
    for v in null_basis:
        trial = np.vstack([combined, v]) if combined.shape[0] else v[None, :]
        if rank(trial) > rank(combined):
            logical_ops.append(v)
            combined = trial
    n = H_detect.shape[1]
    if not logical_ops:
        return np.zeros((0, n), dtype=np.uint8)
    return np.array(logical_ops, dtype=np.uint8)
